//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtgScryfall.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MtgScryfall.UnitTests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;object&quot;: &quot;list&quot;,
        ///    &quot;total_cards&quot;: 26,
        ///    &quot;has_more&quot;: false,
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;object&quot;: &quot;card&quot;,
        ///            &quot;id&quot;: &quot;7241b143-82c9-4f92-b143-b71107f97c60&quot;,
        ///            &quot;oracle_id&quot;: &quot;bb2cc0f4-6abd-48d6-b442-76eafbfd2309&quot;,
        ///            &quot;multiverse_ids&quot;: [
        ///                394069
        ///            ],
        ///            &quot;name&quot;: &quot;Briber&apos;s Purse&quot;,
        ///            &quot;lang&quot;: &quot;en&quot;,
        ///            &quot;uri&quot;: &quot;https://api.scryfall.com/cards/ugin/217&quot;,
        ///            &quot;scryfall_uri&quot;: &quot;https://scryfall.com/card [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MoneyTestDeserializeData {
            get {
                return ResourceManager.GetString("MoneyTestDeserializeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;object&quot;:&quot;list&quot;,&quot;has_more&quot;:false,&quot;data&quot;:[{&quot;object&quot;:&quot;set&quot;,&quot;code&quot;:&quot;m19&quot;,&quot;mtgo_code&quot;:&quot;m19&quot;,&quot;name&quot;:&quot;Core Set 2019&quot;,&quot;uri&quot;:&quot;https://api.scryfall.com/sets/m19&quot;,&quot;scryfall_uri&quot;:&quot;https://scryfall.com/sets/m19&quot;,&quot;search_uri&quot;:&quot;https://api.scryfall.com/cards/search?order=set\u0026q=e%3Am19\u0026unique=prints&quot;,&quot;released_at&quot;:&quot;2018-07-13&quot;,&quot;set_type&quot;:&quot;core&quot;,&quot;card_count&quot;:37,&quot;digital&quot;:false,&quot;foil_only&quot;:false,&quot;icon_svg_uri&quot;:&quot;https://assets.scryfall.com/assets/sets/m19.svg&quot;},{&quot;object&quot;:&quot;set&quot;,&quot;code&quot;:&quot;gs1&quot;,&quot;name&quot;:&quot;Global Series Ji [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetDataJson {
            get {
                return ResourceManager.GetString("SetDataJson", resourceCulture);
            }
        }
    }
}
